SELECT * FROM T_SCP_CONSULTA 
INNER JOIN T_SCP_PACIENTE ON(T_SCP_CONSULTA.CD_PACIENTE = T_SCP_PACIENTE.CD_PACIENTE) 
INNER JOIN T_SCP_USUARIO ON(T_SCP_PACIENTE.CD_PACIENTE = T_SCP_USUARIO.CD_USUARIO) 
INNER JOIN T_SCP_PSICOLOGO ON(T_SCP_CONSULTA.CD_PSICOLOGO_ON = T_SCP_PSICOLOGO.CD_PSICOLOGO) 
INNER JOIN T_SCP_PSI_ONLINE ON(T_SCP_PSICOLOGO.CD_PSICOLOGO = T_SCP_PSI_ONLINE.CD_PSICOLOGO_ON) WHERE T_SCP_CONSULTA.CD_PSICOLOGO_ON >0
;


SELECT * FROM T_SCP_CONSULTA 

INNER JOIN T_SCP_PSICOLOGO ON(T_SCP_CONSULTA.CD_PSICOLOGO_ON = T_SCP_PSICOLOGO.CD_PSICOLOGO) 
INNER JOIN T_SCP_PSI_ONLINE ON(T_SCP_PSICOLOGO.CD_PSICOLOGO = T_SCP_PSI_ONLINE.CD_PSICOLOGO_ON)
INNER JOIN T_SCP_USUARIO ON(T_SCP_PACIENTE.CD_PACIENTE = T_SCP_USUARIO.CD_USUARIO) WHERE T_SCP_CONSULTA.CD_PSICOLOGO_ON >0
;